### PR TITLE
resize_image parameter fix in build_model()

### LINKED ISSUE #6: Training example does not run
The README.md says to run `python main.py --dataset celebA --is_train True --is_crop True`. But when I do this it crashes with the error:
```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    tf.app.run()
  File "/usr/local/anaconda2/envs/subpixel/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 39, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/develop/nets/subpixel/model.py", line 58, in __init__
    self.build_model()
  File "/develop/nets/subpixel/model.py", line 64, in build_model
    self.up_inputs = tf.image.resize_images(self.inputs, self.image_shape[0], self.image_shape[1], tf.image.ResizeMethod.NEAREST_NEIGHBOR)
  File "/usr/local/anaconda2/envs/subpixel/lib/python2.7/site-packages/tensorflow/python/ops/image_ops.py", line 787, in resize_images
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
```

Running the same example from the [carpedm20/DCGAN-tensorflow](https://github.com/carpedm20/DCGAN-tensorflow) repo works fine for me.

### PR DESCRIPTION
**Pull request by dribnet**
Fixes #6

### CODE REVIEW

**Comment by EderSantana** [comment]
Tom, we could accept this but it breaks for my version. Maybe we should define a function that tries the previous case and excepts to this one? Would you write that?

**Comment by dribnet** [comment]
Sure - I can wrap this change so it works for both of us later today. (FWIW - I'm using the current master branch version of TensorFlow.)

**Comment by EderSantana** [comment]
yeah, I just checked yours is the most modern way to do it.
thanks for the change though (I'll wait to finish my thesis before updating any software again :D )

**Comment by dribnet** [comment]
OK, I finally had time to wrap this right. This works for me, try it and let me know what you think.

**Comment by goldsmith** [comment]
hey, thanks for the pull. i'm getting this unfortunately with your branch:

```
Jonathans-MacBook-Pro:subpixel jgoldsmith$ python main.py --dataset celebA --is_train True --is_crop True
{'batch_size': 64,
 'beta1': 0.5,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'celebA',
 'epoch': 25,
 'image_size': 128,
 'is_crop': True,
 'is_train': True,
 'learning_rate': 0.0002,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 39, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/Users/jgoldsmith/projects/subpixel/model.py", line 58, in __init__
    self.build_model()
  File "/Users/jgoldsmith/projects/subpixel/model.py", line 64, in build_model
    self.up_inputs = tf.image.resize_images(self.inputs, [self.image_shape[0], self.image_shape[1]], tf.image.ResizeMethod.NEAREST_NEIGHBOR)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/image_ops.py", line 769, in resize_images
    raise ValueError('new_height must be a scalar integer')
ValueError: new_height must be a scalar integer
```
maybe reverse the order of the tries? i'm also on ``tensorflow==0.10.0rc0`` btw

**Comment by dribnet** [comment]
Hi @goldsmith - at a glance it appears that you are running the current [Tetrachrome master branch](https://github.com/Tetrachrome/subpixel) and not [my resize_fix branch](https://github.com/dribnet/subpixel/tree/resize_fix). (this is based on the stacktrace - line 64 matches [what is currently there](https://github.com/Tetrachrome/subpixel/blob/030ba504b6293fc1a6117b202f841b99677dd492/model.py#L64) and not [what I have on that line](https://github.com/dribnet/subpixel/blob/87e3d8a0624946c4f4671bc4a6a69c95512f3e6c/model.py#L64)). Can you confirm?

If so, you can merge in my branch or just temporarily paste in the [3-4 lines from the diff](https://github.com/Tetrachrome/subpixel/pull/7/files) to get this working.

**Comment by goldsmith** [comment]
thanks for the contribution!

**Pull request merged**
