### PR TITLE
Fix download command

### PR DESCRIPTION
**Pull request by Dandandan**
This fixes the download command of the celebrity dataset.

### CODE REVIEW

**Comment by EderSantana** [comment]
this happened to me before

**Comment by Dandandan** [comment]
What do you mean? It works with this change.

**Comment by EderSantana** [comment]
i mean that dropbox dropped the link before we have to keep the warning. but I noticed your correction. would you update the PR with the new warning?

**Comment by Dandandan** [comment]
Aha, ok :) will do that tomorrow!

**Comment by EderSantana** [comment]
thank you!!!

**Pull request merged**
